from __future__ import annotations

import datetime as _dt
import difflib
import html
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import uuid
from pathlib import Path
from typing import Any
from fastapi import APIRouter
from fastapi.responses import HTMLResponse

_SAFE_NAME = re.compile(r"^[a-z0-9][a-z0-9_-]{1,62}[a-z0-9]$")
_SAFE_RUN_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{1,94}[A-Za-z0-9]$")
_DEFAULT_DESCRIPTION = "Optimized Hermes skill generated by SkillOpt."

router = APIRouter()
requires_auth = False


@router.post("/runs")
def skillopt_create_run(payload: dict[str, Any]):
    return create_run(payload)


@router.post("/runs/train")
def skillopt_train_run(payload: dict[str, Any]):
    return train_run(payload)


@router.get("/ui", response_class=HTMLResponse)
def skillopt_ui():
    return review_html()


@router.post("/evals")
def skillopt_create_eval(payload: dict[str, Any]):
    return create_eval(payload)


@router.get("/evals")
def skillopt_list_evals():
    return list_evals()


@router.get("/evals/{eval_id}")
def skillopt_get_eval(eval_id: str):
    return get_eval(eval_id)


@router.get("/runs")
def skillopt_list_runs():
    return list_runs()


@router.get("/runs/{run_id}")
def skillopt_get_run(run_id: str):
    return get_run(run_id)


@router.get("/runs/{run_id}/diff")
def skillopt_get_run_diff(run_id: str):
    return get_diff(run_id)


@router.get("/runs/{run_id}/review", response_class=HTMLResponse)
def skillopt_get_run_review(run_id: str):
    return review_html(run_id)


@router.get("/runs/{run_id}/files/{filename}")
def skillopt_get_run_file(run_id: str, filename: str):
    return get_file(run_id, filename)


@router.post("/runs/{run_id}/evaluate")
def skillopt_evaluate_run(run_id: str, payload: dict[str, Any]):
    return evaluate_run(run_id, payload)


@router.get("/runs/{run_id}/evaluation")
def skillopt_get_evaluation(run_id: str):
    return get_evaluation(run_id)


@router.post("/runs/{run_id}/bundle")
def skillopt_export_bundle(run_id: str):
    return export_bundle(run_id)


@router.post("/runs/{run_id}/import")
def skillopt_import_run(run_id: str, payload: dict[str, Any]):
    return import_candidate(run_id, payload)


def _sidecar_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _data_root() -> Path:
    root = Path(
        str(
            __import__("os").environ.get(
                "APHRODITE_SKILLOPT_DATA_ROOT",
                _sidecar_root() / "data" / "skillopt",
            )
        )
    ).expanduser()
    root.mkdir(parents=True, exist_ok=True)
    return root


def _runs_root() -> Path:
    path = _data_root() / "runs"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _evals_root() -> Path:
    path = _data_root() / "evals"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _json(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text())
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def _now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).isoformat()


def _run_id(prefix: str = "skillopt") -> str:
    ts = _dt.datetime.now(_dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return f"{prefix}-{ts}-{uuid.uuid4().hex[:8]}"


def _safe_skill_name(value: Any) -> str:
    name = str(value or "").strip().lower().replace(" ", "-")
    if not _SAFE_NAME.match(name):
        raise ValueError("skill_name must be 3-64 chars: lowercase letters, numbers, hyphens, underscores")
    return name


def _read_best_skill(payload: dict[str, Any]) -> str | None:
    inline = payload.get("best_skill_md")
    if isinstance(inline, str) and inline.strip():
        return inline.strip() + "\n"

    for key in ("best_skill_path", "skillopt_output_dir"):
        raw = str(payload.get(key) or "").strip()
        if not raw:
            continue
        path = Path(raw).expanduser()
        if path.is_dir():
            path = path / "best_skill.md"
        if not path.exists() or not path.is_file():
            raise ValueError(f"{key} does not point to an existing best_skill.md file")
        return path.read_text()
    return None


def _read_source_skill(payload: dict[str, Any]) -> str:
    raw = str(payload.get("source_skill_path") or "").strip()
    if not raw:
        return ""
    path = Path(raw).expanduser()
    if not path.exists() or not path.is_file():
        raise ValueError("source_skill_path does not point to an existing file")
    return path.read_text()


def _frontmatter(skill_name: str, description: str, tags: list[str] | None = None) -> str:
    tags = tags or ["skillopt", "optimized-skill"]
    tag_text = ", ".join(tags)
    return (
        "---\n"
        f"name: {skill_name}\n"
        f"description: \"{description}\"\n"
        "version: 1.0.0\n"
        "author: SkillOpt + Aphrodite\n"
        "license: MIT\n"
        "platforms: [linux, macos, windows]\n"
        "metadata:\n"
        "  hermes:\n"
        f"    tags: [{tag_text}]\n"
        "    category: generated\n"
        "    related_skills: []\n"
        "---\n\n"
    )


def wrap_hermes_skill(*, best_skill_md: str, skill_name: str, description: str | None = None) -> str:
    skill_name = _safe_skill_name(skill_name)
    body = str(best_skill_md or "").strip()
    if not body:
        raise ValueError("best_skill_md is required")
    if body.startswith("---\n"):
        return body + ("\n" if not body.endswith("\n") else "")
    return _frontmatter(skill_name, description or _DEFAULT_DESCRIPTION) + body + "\n"


def create_run(payload: dict[str, Any]) -> dict[str, Any]:
    try:
        return _create_run_impl(payload)
    except ValueError as exc:
        return {"ok": False, "error_type": "invalid_argument", "error": str(exc)}
    except OSError as exc:
        return {"ok": False, "error_type": "io_error", "error": str(exc)}


def _create_run_impl(payload: dict[str, Any]) -> dict[str, Any]:
    payload = dict(payload or {})
    skill_name = _safe_skill_name(payload.get("skill_name") or "skillopt-candidate")
    run_id = _safe_run_id(payload.get("run_id"), prefix="skillopt")
    run_dir = _runs_root() / run_id
    if run_dir.exists():
        return {"ok": False, "error_type": "already_exists", "error": "run_id already exists", "run_id": run_id}
    run_dir.mkdir(parents=True)

    request = {k: v for k, v in payload.items() if k not in {"best_skill_md"}}
    request.update({"created_at": _now(), "skill_name": skill_name, "run_id": run_id})
    _write_json(run_dir / "request.json", request)

    source_skill = _read_source_skill(payload)
    if source_skill:
        (run_dir / "source_skill.md").write_text(source_skill)

    best_skill = _read_best_skill(payload)
    candidate_written = False
    if best_skill is not None:
        (run_dir / "best_skill.md").write_text(best_skill)
        candidate = wrap_hermes_skill(
            best_skill_md=best_skill,
            skill_name=skill_name,
            description=str(payload.get("description") or _DEFAULT_DESCRIPTION),
        )
        (run_dir / "candidate_SKILL.md").write_text(candidate)
        candidate_written = True
        old = source_skill.splitlines(keepends=True)
        new = candidate.splitlines(keepends=True)
        diff = "".join(
            difflib.unified_diff(old, new, fromfile="source_skill.md", tofile="candidate_SKILL.md")
        )
        (run_dir / "diff.md").write_text(diff or "# SkillOpt candidate\n\nNo source skill was supplied for diffing.\n")

    status = {
        "ok": True,
        "run_id": run_id,
        "status": "candidate_ready" if candidate_written else "created",
        "run_dir": str(run_dir),
        "skill_name": skill_name,
        "candidate_ready": candidate_written,
        "created_at": request["created_at"],
    }
    _write_json(run_dir / "status.json", status)
    _write_discord_card(run_dir)
    return status


def list_runs() -> dict[str, Any]:
    runs = []
    for path in sorted(_runs_root().iterdir(), reverse=True):
        if path.is_dir():
            status = _json(path / "status.json") or {"run_id": path.name, "status": "unknown"}
            status["run_dir"] = str(path)
            runs.append(status)
    return {"ok": True, "runs": runs, "count": len(runs)}


def get_run(run_id: str) -> dict[str, Any]:
    try:
        safe = _safe_run_id(run_id, required=True)
    except ValueError as exc:
        return {"ok": False, "error_type": "invalid_argument", "error": str(exc), "run_id": str(run_id or "").strip()}
    run_dir = _runs_root() / safe
    if not run_dir.exists() or not run_dir.is_dir():
        return {"ok": False, "error_type": "not_found", "error": "SkillOpt run not found", "run_id": safe}
    files = sorted(p.name for p in run_dir.iterdir() if p.is_file())
    status = _json(run_dir / "status.json") or {"run_id": safe, "status": "unknown"}
    return {"ok": True, "run_id": safe, "run_dir": str(run_dir), "status": status, "files": files}


def get_diff(run_id: str) -> dict[str, Any]:
    detail = get_run(run_id)
    if not detail.get("ok"):
        return detail
    path = Path(detail["run_dir"]) / "diff.md"
    if not path.exists():
        return {"ok": False, "error_type": "not_ready", "error": "diff.md is not available", "run_id": run_id}
    return {"ok": True, "run_id": run_id, "diff": path.read_text()}


def _profile_home(payload: dict[str, Any]) -> Path:
    raw = str(payload.get("profile_home") or "").strip()
    if raw:
        path = Path(raw).expanduser()
    else:
        path = Path.home() / ".hermes"
    path.mkdir(parents=True, exist_ok=True)
    return path


def import_candidate(run_id: str, payload: dict[str, Any]) -> dict[str, Any]:
    payload = dict(payload or {})
    detail = get_run(run_id)
    if not detail.get("ok"):
        return detail
    run_dir = Path(detail["run_dir"])
    candidate = run_dir / "candidate_SKILL.md"
    if not candidate.exists():
        return {"ok": False, "error_type": "not_ready", "error": "candidate_SKILL.md is not available", "run_id": run_id}
    skill_name = _safe_skill_name(payload.get("skill_name") or detail.get("status", {}).get("skill_name") or "skillopt-candidate")
    profile_home = _profile_home(payload)
    dest = profile_home / "skills" / "generated" / skill_name / "SKILL.md"
    if dest.exists() and not bool(payload.get("replace")):
        return {
            "ok": False,
            "error_type": "exists",
            "error": "destination skill exists; pass replace=true to overwrite",
            "destination": str(dest),
        }
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        backup = dest.with_suffix(".md.bak")
        shutil.copy2(dest, backup)
    dest.write_text(candidate.read_text())
    status = _json(run_dir / "status.json")
    status.update({"status": "imported", "imported_at": _now(), "destination": str(dest), "profile_home": str(profile_home)})
    _write_json(run_dir / "status.json", status)
    return {
        "ok": True,
        "run_id": run_id,
        "status": "imported",
        "destination": str(dest),
        "profile_home": str(profile_home),
        "activation": "Start a fresh Hermes session or /reset before expecting this skill to load.",
    }


def _safe_run_id(value: Any, *, prefix: str = "skillopt", required: bool = False) -> str:
    raw = str(value or "").strip()
    if not raw:
        if required:
            raise ValueError("run_id is required")
        return _run_id(prefix)
    if "/" in raw or "\\" in raw or raw in {".", ".."} or ".." in raw:
        raise ValueError("run_id must be a filesystem-safe name, not a path")
    if not _SAFE_RUN_ID.match(raw):
        raise ValueError("run_id must be 3-96 chars: letters, numbers, hyphens, underscores")
    return raw


def _resolve_under(root: Path, candidate: Any, *, default_name: str | None = None) -> Path:
    raw = str(candidate or "").strip()
    path = (root / default_name) if (not raw and default_name) else Path(raw).expanduser()
    if not path.is_absolute():
        path = root / path
    resolved_root = root.resolve()
    resolved = path.resolve()
    if resolved != resolved_root and resolved_root not in resolved.parents:
        raise ValueError("path must stay inside the SkillOpt run directory")
    return resolved


def _copy_optional_file(src_raw: Any, dest: Path, *, label: str) -> None:
    raw = str(src_raw or "").strip()
    if not raw:
        return
    src = Path(raw).expanduser()
    if not src.exists() or not src.is_file():
        raise ValueError(f"{label} does not point to an existing file")
    shutil.copy2(src, dest)


def _score_value(scores: dict[str, Any], *names: str) -> float | None:
    for name in names:
        value = scores.get(name)
        if isinstance(value, (int, float)):
            return float(value)
        if isinstance(value, str):
            try:
                return float(value)
            except ValueError:
                pass
    return None


def _load_scores(run_dir: Path) -> dict[str, Any]:
    scores = _json(run_dir / "scores.json")
    if scores:
        return scores
    history = _json(run_dir / "history.json")
    if isinstance(history.get("scores"), dict):
        return history["scores"]
    return {}


def _write_discord_card(run_dir: Path) -> dict[str, Any]:
    status = _json(run_dir / "status.json")
    request = _json(run_dir / "request.json")
    scores = _load_scores(run_dir)
    baseline = _score_value(scores, "baseline", "baseline_score", "before")
    candidate = _score_value(scores, "candidate", "candidate_score", "best", "after")
    delta = None if baseline is None or candidate is None else candidate - baseline
    title = f"SkillOpt run {status.get('status', 'updated')}: {status.get('skill_name') or request.get('skill_name') or run_dir.name}"
    lines = [title, ""]
    if baseline is not None:
        lines.append(f"Baseline: {baseline:g}")
    if candidate is not None:
        lines.append(f"Candidate: {candidate:g}")
    if delta is not None:
        sign = "+" if delta >= 0 else ""
        lines.append(f"Delta: {sign}{delta:g}")
    lines.append("")
    lines.append(f"Run: {run_dir.name}")
    evaluation = status.get("evaluation") if isinstance(status.get("evaluation"), dict) else {}
    if evaluation:
        lines.append(f"Eval gate: {evaluation.get('status')} · delta={evaluation.get('delta')}")
    if status.get("candidate_ready") or status.get("status") in {"recommended", "rejected_by_eval"}:
        lines.append("Actions: [Open review] [View diff] [Import as candidate] [Reject]")
    else:
        lines.append("Actions: [Open review] [View logs]")
    card = {
        "content": "\n".join(lines),
        "embeds": [
            {
                "title": title[:256],
                "description": f"Run `{run_dir.name}` is `{status.get('status', 'unknown')}`.",
                "fields": [
                    {"name": "Skill", "value": str(status.get("skill_name") or request.get("skill_name") or "unknown"), "inline": True},
                    {"name": "Status", "value": str(status.get("status", "unknown")), "inline": True},
                    {"name": "Run dir", "value": str(run_dir), "inline": False},
                ],
            }
        ],
        "components": [
            {
                "type": 1,
                "components": [
                    {"type": 2, "style": 2, "label": "View diff", "custom_id": f"skillopt:v1:diff:{run_dir.name}"},
                    {"type": 2, "style": 2, "label": "Details", "custom_id": f"skillopt:v1:details:{run_dir.name}"},
                ],
            }
        ],
    }
    _write_json(run_dir / "discord_card.json", card)
    return card


def _finalize_candidate_from_output(run_dir: Path, payload: dict[str, Any]) -> None:
    request = _json(run_dir / "request.json")
    skill_name = _safe_skill_name(request.get("skill_name") or payload.get("skill_name") or "skillopt-candidate")
    output_dir = _resolve_under(run_dir, payload.get("output_dir") or request.get("output_dir"), default_name="work")
    best_path = output_dir / "best_skill.md"
    if not best_path.exists():
        alt = run_dir / "best_skill.md"
        if alt.exists():
            best_path = alt
        else:
            return
    best_skill = best_path.read_text()
    if best_path != run_dir / "best_skill.md":
        (run_dir / "best_skill.md").write_text(best_skill)
    source_skill = (run_dir / "source_skill.md").read_text() if (run_dir / "source_skill.md").exists() else ""
    candidate_md = wrap_hermes_skill(
        best_skill_md=best_skill,
        skill_name=skill_name,
        description=str(request.get("description") or payload.get("description") or _DEFAULT_DESCRIPTION),
    )
    (run_dir / "candidate_SKILL.md").write_text(candidate_md)
    diff = "".join(difflib.unified_diff(source_skill.splitlines(True), candidate_md.splitlines(True), fromfile="source_skill.md", tofile="candidate_SKILL.md"))
    (run_dir / "diff.md").write_text(diff or "# SkillOpt candidate\n\nNo source skill was supplied for diffing.\n")
    for name in ("history.json", "scores.json", "config.yaml"):
        src = output_dir / name
        if src.exists() and src.is_file() and not (run_dir / name).exists():
            shutil.copy2(src, run_dir / name)


def _default_train_command(work_dir: Path, output_dir: Path, payload: dict[str, Any]) -> list[str]:
    repo = str(payload.get("skillopt_repo") or os.environ.get("SKILLOPT_REPO") or "").strip()
    if not repo:
        raise ValueError("training requires command=[...] or skillopt_repo/SKILLOPT_REPO")
    repo_path = Path(repo).expanduser()
    train_script = repo_path / "scripts" / "train.py"
    if not train_script.exists():
        raise ValueError("skillopt_repo must contain scripts/train.py, or pass an explicit command")
    cmd = [sys.executable, str(train_script)]
    config_path = str(payload.get("config_path") or "").strip()
    if config_path:
        cmd += ["--config", config_path]
    cmd += ["--output_dir", str(output_dir)]
    extra = payload.get("extra_args") or []
    if not isinstance(extra, list) or not all(isinstance(x, str) for x in extra):
        raise ValueError("extra_args must be a list of strings")
    return cmd + extra


def train_run(payload: dict[str, Any]) -> dict[str, Any]:
    try:
        return _train_run_impl(payload)
    except ValueError as exc:
        return {"ok": False, "error_type": "invalid_argument", "error": str(exc)}
    except OSError as exc:
        return {"ok": False, "error_type": "io_error", "error": str(exc)}


def _train_run_impl(payload: dict[str, Any]) -> dict[str, Any]:
    payload = dict(payload or {})
    skill_name = _safe_skill_name(payload.get("skill_name") or "skillopt-candidate")
    run_id = _safe_run_id(payload.get("run_id"), prefix="skillopt-train")
    run_dir = _runs_root() / run_id
    if run_dir.exists():
        return {"ok": False, "error_type": "already_exists", "error": "run_id already exists", "run_id": run_id}
    run_dir.mkdir(parents=True)
    work_dir = _resolve_under(run_dir, payload.get("work_dir"), default_name="work")
    output_dir = _resolve_under(run_dir, payload.get("output_dir"), default_name="work")
    work_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)
    request = {k: v for k, v in payload.items() if k not in {"env", "secrets"}}
    request.update({"created_at": _now(), "started_at": _now(), "run_id": run_id, "skill_name": skill_name, "work_dir": str(work_dir), "output_dir": str(output_dir), "v2": True})
    _write_json(run_dir / "request.json", request)
    _copy_optional_file(payload.get("source_skill_path"), run_dir / "source_skill.md", label="source_skill_path")
    _copy_optional_file(payload.get("dataset_manifest_path"), run_dir / "dataset_manifest.json", label="dataset_manifest_path")
    if isinstance(payload.get("config_yaml"), str) and payload["config_yaml"].strip():
        (run_dir / "config.yaml").write_text(payload["config_yaml"].strip() + "\n")
    command = payload.get("command")
    if command is None:
        command = _default_train_command(work_dir, output_dir, payload)
    if not isinstance(command, list) or not command or not all(isinstance(x, str) and x for x in command):
        raise ValueError("command must be a non-empty list of strings")
    timeout = int(payload.get("timeout_seconds") or 900)
    if timeout < 1 or timeout > 7200:
        raise ValueError("timeout_seconds must be between 1 and 7200")
    status = {"ok": True, "run_id": run_id, "status": "running", "run_dir": str(run_dir), "skill_name": skill_name, "candidate_ready": False, "created_at": request["created_at"], "started_at": request["started_at"]}
    _write_json(run_dir / "status.json", status)
    logs_path = run_dir / "logs.txt"
    proc_env = os.environ.copy()
    env = payload.get("env") or {}
    if env:
        if not isinstance(env, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in env.items()):
            raise ValueError("env must be an object of string keys and string values")
        proc_env.update(env)
    try:
        result = subprocess.run(command, cwd=str(work_dir), env=proc_env, text=True, capture_output=True, timeout=timeout, check=False)
        logs_path.write_text((result.stdout or "") + ("\n--- STDERR ---\n" if result.stderr else "") + (result.stderr or ""))
        _finalize_candidate_from_output(run_dir, payload)
        candidate_ready = (run_dir / "candidate_SKILL.md").exists()
        status.update({"finished_at": _now(), "exit_code": result.returncode, "candidate_ready": candidate_ready, "status": "candidate_ready" if result.returncode == 0 and candidate_ready else ("failed" if result.returncode else "completed_no_candidate")})
    except subprocess.TimeoutExpired as exc:
        logs_path.write_text(((exc.stdout or "") if isinstance(exc.stdout, str) else "") + "\n--- TIMEOUT ---\n" + str(exc))
        status.update({"finished_at": _now(), "exit_code": None, "candidate_ready": False, "status": "failed", "error": "training command timed out"})
    _write_json(run_dir / "status.json", status)
    _write_discord_card(run_dir)
    return status


_FORBIDDEN_POLICY_PATTERNS = {
    "silent_skill_mutation": re.compile(r"\b(silently|automatically)\s+(overwrite|replace|mutate)\b.*\b(skill|SKILL\.md)\b", re.I | re.S),
    "casual_gateway_restart": re.compile(r"\b(restart|reload)\b.*\b(gateway|hermes gateway)\b.*\b(without approval|automatically|always)\b", re.I | re.S),
    "operator_domain_policy": re.compile(r"\b(operator|deployment|workspace)\b.*\b(decide|own|set)\b.*\b(pricing|positioning|personal routine|market thesis)\b", re.I | re.S),
}


def _safe_eval_id(value: Any) -> str:
    raw = str(value or "").strip().lower().replace(" ", "-")
    if "/" in raw or "\\" in raw or raw in {".", ".."} or ".." in raw:
        raise ValueError("eval_id must be a filesystem-safe name, not a path")
    if not _SAFE_NAME.match(raw):
        raise ValueError("eval_id must be 3-64 chars: lowercase letters, numbers, hyphens, underscores")
    return raw


def create_eval(payload: dict[str, Any]) -> dict[str, Any]:
    try:
        payload = dict(payload or {})
        eval_id = _safe_eval_id(payload.get("eval_id") or payload.get("name"))
        eval_dir = _evals_root() / eval_id
        if eval_dir.exists() and not bool(payload.get("replace")):
            return {"ok": False, "error_type": "exists", "error": "eval_id already exists; pass replace=true", "eval_id": eval_id}
        eval_dir.mkdir(parents=True, exist_ok=True)
        raw_manifest = payload.get("manifest") or {}
        if not isinstance(raw_manifest, dict):
            raise ValueError("manifest must be an object")
        manifest = dict(raw_manifest)
        manifest.update({
            "eval_id": eval_id,
            "skill_family": str(payload.get("skill_family") or manifest.get("skill_family") or eval_id),
            "scorer": str(payload.get("scorer") or manifest.get("scorer") or "score_delta"),
            "min_delta": float(payload.get("min_delta", manifest.get("min_delta", 0.0)) or 0.0),
            "created_at": manifest.get("created_at") or _now(),
        })
        _write_json(eval_dir / "manifest.json", manifest)
        if isinstance(payload.get("cases_jsonl"), str):
            (eval_dir / "cases.jsonl").write_text(payload["cases_jsonl"].strip() + "\n")
        if isinstance(payload.get("rubric_md"), str):
            (eval_dir / "rubric.md").write_text(payload["rubric_md"].strip() + "\n")
        return {"ok": True, "eval_id": eval_id, "eval_dir": str(eval_dir), "manifest": manifest}
    except ValueError as exc:
        return {"ok": False, "error_type": "invalid_argument", "error": str(exc)}
    except OSError as exc:
        return {"ok": False, "error_type": "io_error", "error": str(exc)}


def list_evals() -> dict[str, Any]:
    evals = []
    for path in sorted(_evals_root().iterdir(), reverse=True):
        if path.is_dir():
            manifest = _json(path / "manifest.json") or {"eval_id": path.name}
            manifest["eval_dir"] = str(path)
            evals.append(manifest)
    return {"ok": True, "evals": evals, "count": len(evals)}


def get_eval(eval_id: str) -> dict[str, Any]:
    try:
        safe = _safe_eval_id(eval_id)
    except ValueError as exc:
        return {"ok": False, "error_type": "invalid_argument", "error": str(exc)}
    eval_dir = _evals_root() / safe
    if not eval_dir.exists() or not eval_dir.is_dir():
        return {"ok": False, "error_type": "not_found", "error": "SkillOpt eval not found", "eval_id": safe}
    files = sorted(p.name for p in eval_dir.iterdir() if p.is_file())
    return {"ok": True, "eval_id": safe, "eval_dir": str(eval_dir), "manifest": _json(eval_dir / "manifest.json"), "files": files}


def _candidate_policy_hits(candidate: str) -> list[dict[str, str]]:
    hits = []
    for code, pattern in _FORBIDDEN_POLICY_PATTERNS.items():
        match = pattern.search(candidate)
        if match:
            excerpt = " ".join(match.group(0).split())[:220]
            hits.append({"code": code, "excerpt": excerpt})
    return hits


def _candidate_format_valid(candidate: str) -> bool:
    return candidate.startswith("---\n") and "\n---\n" in candidate[4:] and "\nname:" in candidate.split("---", 2)[1]


def _evaluation_dir(run_dir: Path) -> Path:
    path = run_dir / "evaluation"
    path.mkdir(parents=True, exist_ok=True)
    return path


def evaluate_run(run_id: str, payload: dict[str, Any]) -> dict[str, Any]:
    try:
        return _evaluate_run_impl(run_id, payload)
    except ValueError as exc:
        return {"ok": False, "error_type": "invalid_argument", "error": str(exc), "run_id": run_id}
    except OSError as exc:
        return {"ok": False, "error_type": "io_error", "error": str(exc), "run_id": run_id}


def _evaluate_run_impl(run_id: str, payload: dict[str, Any]) -> dict[str, Any]:
    payload = dict(payload or {})
    detail = get_run(run_id)
    if not detail.get("ok"):
        return detail
    run_dir = Path(detail["run_dir"])
    candidate_path = run_dir / "candidate_SKILL.md"
    if not candidate_path.exists():
        return {"ok": False, "error_type": "not_ready", "error": "candidate_SKILL.md is not available", "run_id": run_id}
    eval_manifest: dict[str, Any] = {}
    eval_id = str(payload.get("eval_id") or "").strip()
    if eval_id:
        ev = get_eval(eval_id)
        if not ev.get("ok"):
            return ev
        eval_manifest = dict(ev.get("manifest") or {})
    scores = _load_scores(run_dir)
    baseline = _score_value(payload, "baseline_score", "baseline")
    candidate_score = _score_value(payload, "candidate_score", "candidate")
    if baseline is None:
        baseline = _score_value(scores, "baseline_score", "baseline", "before")
    if candidate_score is None:
        candidate_score = _score_value(scores, "candidate_score", "candidate", "best", "after")
    if baseline is None or candidate_score is None:
        raise ValueError("baseline_score and candidate_score are required unless scores.json provides them")
    min_delta = float(payload.get("min_delta", eval_manifest.get("min_delta", 0.0)) or 0.0)
    critical_failures = list(payload.get("critical_failures") or [])
    must_not_regress_failed = list(payload.get("must_not_regress_failed") or [])
    candidate_text = candidate_path.read_text()
    forbidden_hits = _candidate_policy_hits(candidate_text)
    format_valid = _candidate_format_valid(candidate_text)
    delta = candidate_score - baseline
    gate_pass = bool(format_valid and not forbidden_hits and not critical_failures and not must_not_regress_failed and delta >= min_delta)
    status_value = "recommended" if gate_pass else "rejected_by_eval"
    eval_dir = _evaluation_dir(run_dir)
    baseline_results = {"score": baseline}
    candidate_results = {"score": candidate_score, "format_valid": format_valid, "forbidden_policy_hits": forbidden_hits}
    comparison = {
        "ok": True,
        "run_id": run_id,
        "eval_id": eval_id or None,
        "baseline_score": baseline,
        "candidate_score": candidate_score,
        "delta": delta,
        "min_delta": min_delta,
        "gate_pass": gate_pass,
        "status": status_value,
        "critical_failures": critical_failures,
        "must_not_regress_failed": must_not_regress_failed,
        "format_valid": format_valid,
        "forbidden_policy_hits": forbidden_hits,
        "evaluated_at": _now(),
    }
    _write_json(eval_dir / "baseline_results.json", baseline_results)
    _write_json(eval_dir / "candidate_results.json", candidate_results)
    _write_json(eval_dir / "comparison.json", comparison)
    failures = []
    if delta < min_delta:
        failures.append(f"Delta {delta:g} is below required min_delta {min_delta:g}.")
    if not format_valid:
        failures.append("Candidate SKILL.md frontmatter is invalid.")
    failures.extend(f"Critical failure: {x}" for x in critical_failures)
    failures.extend(f"Must-not-regress failed: {x}" for x in must_not_regress_failed)
    failures.extend(f"Forbidden policy drift: {x['code']} — {x['excerpt']}" for x in forbidden_hits)
    (eval_dir / "failures.md").write_text("# Evaluation failures\n\n" + ("\n".join(f"- {x}" for x in failures) if failures else "No blocking failures.\n"))
    recommendation = "Import as generated candidate; do not replace the source skill automatically." if gate_pass else "Do not import yet; inspect failures and rerun SkillOpt/eval."
    (eval_dir / "recommendation.md").write_text(f"# Recommendation\n\n{recommendation}\n")
    status = _json(run_dir / "status.json")
    status.update({"status": status_value, "evaluated_at": comparison["evaluated_at"], "evaluation": comparison})
    _write_json(run_dir / "status.json", status)
    _write_discord_card(run_dir)
    return comparison


def get_evaluation(run_id: str) -> dict[str, Any]:
    detail = get_run(run_id)
    if not detail.get("ok"):
        return detail
    run_dir = Path(detail["run_dir"])
    eval_dir = run_dir / "evaluation"
    if not eval_dir.exists():
        return {"ok": False, "error_type": "not_ready", "error": "evaluation is not available", "run_id": run_id}
    files = sorted(p.name for p in eval_dir.iterdir() if p.is_file())
    return {"ok": True, "run_id": run_id, "evaluation_dir": str(eval_dir), "comparison": _json(eval_dir / "comparison.json"), "files": files}


def export_bundle(run_id: str) -> dict[str, Any]:
    detail = get_run(run_id)
    if not detail.get("ok"):
        return detail
    run_dir = Path(detail["run_dir"])
    bundle = run_dir / f"skillopt-run-{run_id}.tar.gz"
    include = ["source_skill.md", "candidate_SKILL.md", "diff.md", "logs.txt", "scores.json", "history.json", "request.json", "status.json", "discord_card.json"]
    readme = run_dir / "BUNDLE_README.md"
    readme.write_text(f"# SkillOpt run bundle\n\nRun: `{run_id}`\n\nImport remains explicit and generated-skill-only by default.\n")
    with tarfile.open(bundle, "w:gz") as tar:
        tar.add(readme, arcname="README.md")
        for name in include:
            path = run_dir / name
            if path.exists() and path.is_file():
                tar.add(path, arcname=name)
        eval_dir = run_dir / "evaluation"
        if eval_dir.exists():
            for path in sorted(eval_dir.iterdir()):
                if path.is_file():
                    tar.add(path, arcname=f"evaluation/{path.name}")
    return {"ok": True, "run_id": run_id, "bundle": str(bundle)}


def get_file(run_id: str, filename: str) -> dict[str, Any]:
    detail = get_run(run_id)
    if not detail.get("ok"):
        return detail
    allowed = {"logs.txt", "best_skill.md", "candidate_SKILL.md", "history.json", "scores.json", "discord_card.json", "request.json", "status.json", "dataset_manifest.json", "config.yaml", "BUNDLE_README.md"}
    filename = str(filename or "").strip()
    if "/" in filename or "\\" in filename or filename in {".", ".."} or ".." in filename:
        return {"ok": False, "error_type": "invalid_argument", "error": "filename must be a supported file name, not a path", "run_id": detail["run_id"]}
    if filename not in allowed:
        return {"ok": False, "error_type": "invalid_argument", "error": "unsupported file", "run_id": detail["run_id"]}
    path = _resolve_under(Path(detail["run_dir"]), filename)
    if not path.exists() or not path.is_file():
        return {"ok": False, "error_type": "not_found", "error": f"{filename} is not available", "run_id": detail["run_id"]}
    return {"ok": True, "run_id": detail["run_id"], "filename": filename, "content": path.read_text()}


def review_html(run_id: str | None = None) -> str:
    if run_id:
        detail = get_run(run_id)
        if not detail.get("ok"):
            return "<h1>SkillOpt run not found</h1>"
        run_dir = Path(detail["run_dir"])
        status = _json(run_dir / "status.json")
        diff = (run_dir / "diff.md").read_text() if (run_dir / "diff.md").exists() else "Diff is not available yet."
        logs = (run_dir / "logs.txt").read_text() if (run_dir / "logs.txt").exists() else "Logs are not available yet."
        comparison = _json(run_dir / "evaluation" / "comparison.json")
        recommendation = (run_dir / "evaluation" / "recommendation.md").read_text() if (run_dir / "evaluation" / "recommendation.md").exists() else "No evaluation recommendation yet."
        eval_html = "" if not comparison else f"<h2>Evaluation gate</h2><div class='card'><span class='pill'>{html.escape(str(comparison.get('status')))}</span><span class='pill'>delta={html.escape(str(comparison.get('delta')))}</span><span class='pill'>min_delta={html.escape(str(comparison.get('min_delta')))}</span><pre>{html.escape(recommendation)}</pre></div>"
        return """<!doctype html><html><head><meta charset='utf-8'><title>SkillOpt Review</title><style>body{font-family:system-ui;background:#111827;color:#f8fafc;margin:2rem;line-height:1.5}a{color:#93c5fd}.card{background:#1f2937;border:1px solid #374151;border-radius:14px;padding:1rem;margin:1rem 0}pre{white-space:pre-wrap;background:#020617;padding:1rem;border-radius:10px;overflow:auto}.pill{display:inline-block;background:#334155;border-radius:999px;padding:.2rem .6rem;margin:.1rem}</style></head><body>""" + f"<h1>SkillOpt Review: {html.escape(str(status.get('skill_name') or run_id))}</h1><p><a href='/skillopt/ui'>All runs</a></p><div class='card'><span class='pill'>{html.escape(str(status.get('status')))}</span><span class='pill'>candidate_ready={bool(status.get('candidate_ready'))}</span><p>Run dir: <code>{html.escape(str(run_dir))}</code></p></div>{eval_html}<h2>Diff</h2><pre>{html.escape(diff)}</pre><h2>Logs</h2><pre>{html.escape(logs[-20000:])}</pre></body></html>"
    runs = list_runs().get("runs", [])
    items = "".join(f"<li><a href='/skillopt/runs/{html.escape(r.get('run_id',''))}/review'>{html.escape(r.get('run_id',''))}</a> — {html.escape(str(r.get('status')))} — {html.escape(str(r.get('skill_name','')))}</li>" for r in runs)
    return """<!doctype html><html><head><meta charset='utf-8'><title>SkillOpt Runs</title><style>body{font-family:system-ui;background:#111827;color:#f8fafc;margin:2rem}a{color:#93c5fd}li{margin:.5rem 0}</style></head><body><h1>SkillOpt Runs</h1><p>Review-gated Hermes skill optimization artifacts. Import remains explicit through the API.</p><ul>""" + items + "</ul></body></html>"


def handle(action: str, payload: list[str], context: dict[str, Any]) -> dict[str, Any]:
    action = str(action or "").strip().lower()
    payload = list(payload or [])
    if action == "status":
        data = list_runs()
        evals = list_evals()
        data.update({
            "ok": True,
            "ephemeral": True,
            "evals": evals.get("evals", []),
            "eval_count": evals.get("count", 0),
        })
        return data
    if action == "list_runs":
        return list_runs()
    if action == "get_run" and payload:
        return get_run(payload[0])
    if action == "list_evals":
        return list_evals()
    if action == "get_eval" and payload:
        return get_eval(payload[0])
    if action == "diff" and payload:
        return get_diff(payload[0])
    if action == "details" and payload:
        return get_run(payload[0])
    if action == "logs" and payload:
        return get_file(payload[0], "logs.txt")
    if action == "evaluation" and payload:
        return get_evaluation(payload[0])
    if action in {"get_run", "get_eval", "diff", "details", "logs", "evaluation"}:
        return {"ok": False, "error_type": "invalid_argument", "error": f"{action} requires a run_id or eval_id payload", "action": action}
    return {
        "ok": False,
        "error": f"unknown action: {action}",
        "supported_actions": [
            "details",
            "diff",
            "evaluation",
            "get_eval",
            "get_run",
            "list_evals",
            "list_runs",
            "logs",
            "status",
        ],
        "examples": [
            "aphrodite dispatch-test skillopt:v1:status",
            "aphrodite dispatch-test skillopt:v1:list_runs",
        ],
    }
