from __future__ import annotations

import sys

from fastapi.testclient import TestClient

from aphrodite.app import create_app
from aphrodite.modules import skillopt


BEST_SKILL = """# Question Answering Skill\n\n- Prefer concise answers.\n"""
SOURCE_SKILL = """---\nname: old-qa\ndescription: \"Old skill.\"\n---\n\n# Old\n\n- Be vague.\n"""


def test_skillopt_routes_remain_public_and_html_through_create_app(monkeypatch, tmp_path):
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(tmp_path / "data"))
    monkeypatch.setenv("APHRODITE_ADAPTER_AUTH_TOKEN", "secret-token")

    client = TestClient(create_app())
    runs = client.get("/skillopt/runs")
    assert runs.status_code == 200
    assert runs.json() == {"ok": True, "runs": [], "count": 0}

    ui = client.get("/skillopt/ui")
    assert ui.status_code == 200
    assert ui.headers["content-type"].startswith("text/html")
    assert "SkillOpt Runs" in ui.text

    created = client.post(
        "/skillopt/runs",
        json={"run_id": "skillopt-public-html", "skill_name": "public-html", "best_skill_md": BEST_SKILL},
    )
    assert created.status_code == 200
    assert created.json()["ok"] is True

    review = client.get("/skillopt/runs/skillopt-public-html/review")
    assert review.status_code == 200
    assert review.headers["content-type"].startswith("text/html")
    assert "SkillOpt Review" in review.text


def test_skillopt_run_wraps_best_skill_and_imports_candidate(monkeypatch, tmp_path):
    data_root = tmp_path / "skillopt-data"
    profile = tmp_path / "profile"
    source = tmp_path / "source.md"
    source.write_text(SOURCE_SKILL)
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(data_root))

    client = TestClient(create_app())
    response = client.post(
        "/skillopt/runs",
        json={
            "run_id": "skillopt-test-run",
            "skill_name": "qa-optimized",
            "description": "Optimized QA behavior generated by SkillOpt.",
            "source_skill_path": str(source),
            "best_skill_md": BEST_SKILL,
        },
    )

    assert response.status_code == 200
    created = response.json()
    assert created["ok"] is True
    assert created["status"] == "candidate_ready"
    run_dir = data_root / "runs" / "skillopt-test-run"
    candidate = (run_dir / "candidate_SKILL.md").read_text()
    assert candidate.startswith("---\nname: qa-optimized\n")
    assert "# Question Answering Skill" in candidate
    assert "source_skill_path" in (run_dir / "request.json").read_text()
    assert "best_skill_md" not in (run_dir / "request.json").read_text()

    diff = client.get("/skillopt/runs/skillopt-test-run/diff").json()
    assert diff["ok"] is True
    assert "candidate_SKILL.md" in diff["diff"]
    assert "Prefer concise answers" in diff["diff"]

    imported = client.post(
        "/skillopt/runs/skillopt-test-run/import",
        json={"profile_home": str(profile)},
    ).json()
    assert imported["ok"] is True
    destination = profile / "skills" / "generated" / "qa-optimized" / "SKILL.md"
    assert imported["destination"] == str(destination)
    assert destination.read_text() == candidate
    assert "fresh Hermes session" in imported["activation"]


def test_skillopt_import_refuses_overwrite_without_replace(monkeypatch, tmp_path):
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(tmp_path / "data"))
    profile = tmp_path / "profile"
    first = skillopt.create_run(
        {"run_id": "skillopt-overwrite", "skill_name": "same-skill", "best_skill_md": BEST_SKILL}
    )
    assert first["ok"] is True
    assert skillopt.import_candidate("skillopt-overwrite", {"profile_home": str(profile)})["ok"] is True

    refused = skillopt.import_candidate("skillopt-overwrite", {"profile_home": str(profile)})
    assert refused["ok"] is False
    assert refused["error_type"] == "exists"

    replaced = skillopt.import_candidate("skillopt-overwrite", {"profile_home": str(profile), "replace": True})
    assert replaced["ok"] is True


def test_skillopt_rejects_invalid_skill_name_before_writing(monkeypatch, tmp_path):
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(tmp_path / "data"))

    client = TestClient(create_app())
    response = client.post("/skillopt/runs", json={"skill_name": "../bad", "best_skill_md": BEST_SKILL})
    assert response.status_code == 200
    data = response.json()
    assert data["ok"] is False
    assert data["error_type"] == "invalid_argument"
    assert "skill_name" in data["error"]
    assert not (tmp_path / "data" / "runs").exists()


def test_skillopt_dispatch_status_registered(monkeypatch, tmp_path):
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(tmp_path / "data"))

    client = TestClient(create_app())
    response = client.post("/dispatch/skillopt:v1:status")

    assert response.status_code == 200
    data = response.json()
    assert data["ok"] is True
    assert data["system"] == "skillopt"
    assert data["result"]["ok"] is True
    assert data["result"]["count"] == 0


def test_skillopt_v2_train_run_creates_candidate_logs_scores_card_and_review(monkeypatch, tmp_path):
    data_root = tmp_path / "skillopt-data"
    source = tmp_path / "source.md"
    source.write_text(SOURCE_SKILL)
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(data_root))
    fake_train = __import__("pathlib").Path(__file__).parent / "fixtures" / "fake_skillopt_train.py"

    client = TestClient(create_app())
    output_dir = data_root / "runs" / "skillopt-train-test" / "work"
    response = client.post(
        "/skillopt/runs/train",
        json={
            "run_id": "skillopt-train-test",
            "skill_name": "qa-trained",
            "source_skill_path": str(source),
            "dataset_manifest_path": str(source),
            "config_yaml": "max_iters: 1",
            "command": [sys.executable, str(fake_train), str(output_dir)],
            "timeout_seconds": 30,
        },
    )

    assert response.status_code == 200
    trained = response.json()
    assert trained["ok"] is True
    assert trained["status"] == "candidate_ready"
    assert trained["candidate_ready"] is True
    run_dir = data_root / "runs" / "skillopt-train-test"
    assert (run_dir / "best_skill.md").read_text().startswith("# Fake Optimized Skill")
    assert "fake skillopt complete" in (run_dir / "logs.txt").read_text()
    assert "candidate_score" in (run_dir / "scores.json").read_text()
    card = client.get("/skillopt/runs/skillopt-train-test/files/discord_card.json").json()
    assert card["ok"] is True
    assert "Delta: +0.25" in card["content"]
    review = client.get("/skillopt/runs/skillopt-train-test/review")
    assert review.status_code == 200
    assert "SkillOpt Review" in review.text
    assert "Fake Optimized Skill" in review.text


def test_skillopt_v2_train_rejects_path_escape(monkeypatch, tmp_path):
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(tmp_path / "data"))
    client = TestClient(create_app())
    response = client.post(
        "/skillopt/runs/train",
        json={
            "run_id": "skillopt-train-escape",
            "skill_name": "qa-trained",
            "output_dir": "../../outside",
            "command": [sys.executable, "-c", "print('should not run')"],
        },
    )
    data = response.json()
    assert data["ok"] is False
    assert data["error_type"] == "invalid_argument"
    assert "inside the SkillOpt run directory" in data["error"]


def _create_trained_run(client, data_root, source):
    fake_train = __import__("pathlib").Path(__file__).parent / "fixtures" / "fake_skillopt_train.py"
    output_dir = data_root / "runs" / "skillopt-v3-test" / "work"
    response = client.post(
        "/skillopt/runs/train",
        json={
            "run_id": "skillopt-v3-test",
            "skill_name": "qa-v3-trained",
            "source_skill_path": str(source),
            "command": [sys.executable, str(fake_train), str(output_dir)],
            "timeout_seconds": 30,
        },
    )
    assert response.json()["status"] == "candidate_ready"


def test_skillopt_v3_eval_registry_recommends_and_exports_bundle(monkeypatch, tmp_path):
    data_root = tmp_path / "skillopt-data"
    source = tmp_path / "source.md"
    source.write_text(SOURCE_SKILL)
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(data_root))
    client = TestClient(create_app())
    _create_trained_run(client, data_root, source)

    created_eval = client.post(
        "/skillopt/evals",
        json={
            "eval_id": "qa-eval",
            "skill_family": "qa",
            "min_delta": 0.1,
            "cases_jsonl": "{\"id\":\"case-1\"}",
            "rubric_md": "# Rubric",
        },
    ).json()
    assert created_eval["ok"] is True
    assert client.get("/skillopt/evals/qa-eval").json()["manifest"]["min_delta"] == 0.1
    assert client.get("/skillopt/evals").json()["count"] == 1

    evaluation = client.post(
        "/skillopt/runs/skillopt-v3-test/evaluate",
        json={"eval_id": "qa-eval"},
    ).json()
    assert evaluation["ok"] is True
    assert evaluation["status"] == "recommended"
    assert evaluation["gate_pass"] is True
    assert evaluation["delta"] == 0.25

    fetched = client.get("/skillopt/runs/skillopt-v3-test/evaluation").json()
    assert fetched["ok"] is True
    assert "recommendation.md" in fetched["files"]
    detail = client.get("/skillopt/runs/skillopt-v3-test").json()
    assert detail["status"]["status"] == "recommended"
    card = client.get("/skillopt/runs/skillopt-v3-test/files/discord_card.json").json()["content"]
    assert "Eval gate: recommended" in card
    review = client.get("/skillopt/runs/skillopt-v3-test/review")
    assert "Evaluation gate" in review.text
    assert "Import as generated candidate" in review.text
    bundle = client.post("/skillopt/runs/skillopt-v3-test/bundle").json()
    assert bundle["ok"] is True
    assert __import__("pathlib").Path(bundle["bundle"]).exists()


def test_skillopt_v3_eval_rejects_regression_and_forbidden_policy(monkeypatch, tmp_path):
    data_root = tmp_path / "skillopt-data"
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(data_root))
    client = TestClient(create_app())
    created = client.post(
        "/skillopt/runs",
        json={
            "run_id": "skillopt-v3-bad",
            "skill_name": "qa-bad",
            "best_skill_md": "# Bad\n\n- Automatically overwrite production skill files silently.\n",
        },
    ).json()
    assert created["ok"] is True
    rejected = client.post(
        "/skillopt/runs/skillopt-v3-bad/evaluate",
        json={
            "baseline_score": 0.8,
            "candidate_score": 0.81,
            "min_delta": 0.05,
            "must_not_regress_failed": ["legacy-url-repair"],
        },
    ).json()
    assert rejected["status"] == "rejected_by_eval"
    assert rejected["gate_pass"] is False
    assert rejected["must_not_regress_failed"] == ["legacy-url-repair"]
    assert rejected["forbidden_policy_hits"][0]["code"] == "silent_skill_mutation"


def test_skillopt_dispatch_exposes_read_only_run_and_eval_actions(monkeypatch, tmp_path):
    data_root = tmp_path / "skillopt-data"
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(data_root))
    created = skillopt.create_run(
        {"run_id": "skillopt-dispatch-run", "skill_name": "dispatch-skill", "best_skill_md": BEST_SKILL}
    )
    created_eval = skillopt.create_eval({"eval_id": "dispatch-eval", "min_delta": 0.2})
    assert created["ok"] is True
    assert created_eval["ok"] is True

    client = TestClient(create_app())
    status = client.post("/dispatch/skillopt:v1:status").json()["result"]
    assert status["ok"] is True
    assert status["count"] == 1
    assert status["eval_count"] == 1
    assert status["runs"][0]["run_id"] == "skillopt-dispatch-run"
    assert status["evals"][0]["eval_id"] == "dispatch-eval"

    listed_runs = client.post("/dispatch/skillopt:v1:list_runs").json()["result"]
    assert listed_runs == skillopt.list_runs()
    fetched_run = client.post("/dispatch/skillopt:v1:get_run:skillopt-dispatch-run").json()["result"]
    assert fetched_run == skillopt.get_run("skillopt-dispatch-run")
    listed_evals = client.post("/dispatch/skillopt:v1:list_evals").json()["result"]
    assert listed_evals == skillopt.list_evals()
    fetched_eval = client.post("/dispatch/skillopt:v1:get_eval:dispatch-eval").json()["result"]
    assert fetched_eval == skillopt.get_eval("dispatch-eval")


def test_skillopt_generated_run_id_can_be_fetched(monkeypatch, tmp_path):
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(tmp_path / "data"))
    created = skillopt.create_run({"skill_name": "generated-id", "best_skill_md": BEST_SKILL})
    assert created["ok"] is True

    fetched = skillopt.get_run(created["run_id"])
    assert fetched["ok"] is True
    assert fetched["run_id"] == created["run_id"]


def test_skillopt_dispatch_validation_rejects_malformed_and_path_ids(monkeypatch, tmp_path):
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(tmp_path / "data"))
    client = TestClient(create_app())

    bad_run = skillopt.handle("get_run", ["../outside"], {})
    assert bad_run["ok"] is False
    assert bad_run["error_type"] == "invalid_argument"
    assert "not a path" in bad_run["error"]

    malformed_run = client.post("/dispatch/skillopt:v1:get_run:bad!id").json()["result"]
    assert malformed_run["ok"] is False
    assert malformed_run["error_type"] == "invalid_argument"
    assert "run_id" in malformed_run["error"]

    bad_eval = skillopt.handle("get_eval", ["../outside"], {})
    assert bad_eval["ok"] is False
    assert bad_eval["error_type"] == "invalid_argument"
    assert "not a path" in bad_eval["error"]

    malformed_eval = client.post("/dispatch/skillopt:v1:get_eval:bad!id").json()["result"]
    assert malformed_eval["ok"] is False
    assert malformed_eval["error_type"] == "invalid_argument"
    assert "eval_id" in malformed_eval["error"]

    missing_payload = client.post("/dispatch/skillopt:v1:get_run").json()["result"]
    assert missing_payload["ok"] is False
    assert missing_payload["error_type"] == "invalid_argument"


def test_skillopt_create_and_train_error_envelopes_are_consistent(monkeypatch, tmp_path):
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(tmp_path / "data"))

    created = skillopt.create_run({"run_id": "../escape", "skill_name": "safe-skill"})
    assert created["ok"] is False
    assert created["error_type"] == "invalid_argument"
    assert "not a path" in created["error"]
    assert not (tmp_path / "data" / "runs").exists()

    trained = skillopt.train_run({"run_id": "bad!id", "skill_name": "safe-skill"})
    assert trained["ok"] is False
    assert trained["error_type"] == "invalid_argument"
    assert "run_id" in trained["error"]
    train_io = skillopt.train_run(
        {"run_id": "skillopt-missing-command", "skill_name": "safe-skill", "command": [str(tmp_path / "missing")]}
    )
    assert train_io["ok"] is False
    assert train_io["error_type"] == "io_error"

    eval_result = skillopt.create_eval({"eval_id": "../escape"})
    assert eval_result["ok"] is False
    assert eval_result["error_type"] == "invalid_argument"
    assert "not a path" in eval_result["error"]

    bad_manifest = skillopt.create_eval({"eval_id": "manifest_bad", "manifest": 123})
    assert bad_manifest["ok"] is False
    assert bad_manifest["error_type"] == "invalid_argument"

    evaluated = skillopt.evaluate_run("../escape", {"baseline_score": 0.1, "candidate_score": 0.2})
    assert evaluated["ok"] is False
    assert evaluated["error_type"] == "invalid_argument"
    assert "not a path" in evaluated["error"]


def test_skillopt_file_validation_rejects_path_traversal_filename(monkeypatch, tmp_path):
    data_root = tmp_path / "skillopt-data"
    monkeypatch.setenv("APHRODITE_SKILLOPT_DATA_ROOT", str(data_root))
    created = skillopt.create_run(
        {"run_id": "skillopt-file-safe", "skill_name": "file-safe", "best_skill_md": BEST_SKILL}
    )
    assert created["ok"] is True

    rejected = skillopt.get_file("skillopt-file-safe", "../status.json")
    assert rejected["ok"] is False
    assert rejected["error_type"] == "invalid_argument"
    assert "not a path" in rejected["error"]

    accepted = skillopt.get_file("skillopt-file-safe", "status.json")
    assert accepted["ok"] is True
    assert accepted["filename"] == "status.json"
